- hosts: "{{hostname}}"
  become: yes
  tasks:
  - name: Install the check-mk agent
    ansible.builtin.yum:
      disable_gpg_check: true
      validate_certs: false
      name: http://192.168.100.15/mysite/check_mk/agents/check-mk-agent-2.1.0p4-1.noarch.rpm
      state: present
  - name: Enable TLS
    #remote_src: yes
    shell: cmk-agent-ctl register --hostname {{hostname}} --server 192.168.100.15 --site mysite --user automation --password i932i0c4h5Ogyq9FUwoZ
  