- hosts: "{{hostname}}"
  become: yes
  tasks:
  - name: Remove getUpdates
    ansible.builtin.file:
      path: /bin/getUpdates
      state: absent
  - name: Remove postUpdates
    ansible.builtin.file:
      path: /bin/postUpdates
      state: absent
  - name: Download getUpdates
    ansible.builtin.get_url:
      url: http://192.168.100.11/update-agent/getUpdates
      dest: /bin/getUpdates
      mode: 'a+x'
  - name: Download postUpdates
    ansible.builtin.get_url:
      url: http://192.168.100.11/update-agent/postUpdates
      dest: /bin/postUpdates
      mode: 'a+x'
  - name: Add the client key
    replace:
      path: /bin/postUpdates
      regexp: 'clientkey'
      replace: "{{clientkey}}"
  - name: Run CRON job to post updates at every 30th minute of every hour.
    become_method: sudo
    cron:
      name: "Post_updates"
      user: "root"
      weekday: "*"
      minute: "30"
      hour: "*"
      job: "/bin/postUpdates"
      state: present
  - name: Send the first report
    remote_src: yes
    ansible.builtin.command: sh /bin/postUpdates
