- hosts: "{{hostname}}"
  become: yes
  tasks:
  - name: upgrade all packages
    yum: name=* state=latest
  - name: Reboot a slow machine that might have lots of updates to apply
    ansible.builtin.reboot:
      reboot_timeout: 3600
